USE [master]
GO

/****** Object:  Database [HardwareInventory]    Script Date: 2020/05/05 18:10:47 ******/
CREATE DATABASE [HardwareInventory]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'HardwareInventory', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HardwareInventory.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'HardwareInventory_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\HardwareInventory_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [HardwareInventory].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [HardwareInventory] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [HardwareInventory] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [HardwareInventory] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [HardwareInventory] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [HardwareInventory] SET ARITHABORT OFF 
GO

ALTER DATABASE [HardwareInventory] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [HardwareInventory] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [HardwareInventory] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [HardwareInventory] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [HardwareInventory] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [HardwareInventory] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [HardwareInventory] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [HardwareInventory] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [HardwareInventory] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [HardwareInventory] SET  DISABLE_BROKER 
GO

ALTER DATABASE [HardwareInventory] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [HardwareInventory] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [HardwareInventory] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [HardwareInventory] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [HardwareInventory] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [HardwareInventory] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [HardwareInventory] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [HardwareInventory] SET RECOVERY FULL 
GO

ALTER DATABASE [HardwareInventory] SET  MULTI_USER 
GO

ALTER DATABASE [HardwareInventory] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [HardwareInventory] SET DB_CHAINING OFF 
GO

ALTER DATABASE [HardwareInventory] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [HardwareInventory] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [HardwareInventory] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [HardwareInventory] SET QUERY_STORE = OFF
GO

ALTER DATABASE [HardwareInventory] SET  READ_WRITE 
GO


